export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';
export const ORDER_ALL_REQUEST = 'ORDER_ALL_REQUEST';
export const ORDER_ALL_SUCCESS = 'ORDER_ALL_SUCCESS';
export const ORDER_ALL_FAIL = 'ORDER_ALL_FAIL';