const data = {
    products: [
      {
        _id: '1',
        name: 'Nike Slim Shirt',
        category: 'Shirts',
        image: 'https://images.bewakoof.com/t320/black-white-chest-panel-zipper-sweatshirt-hoodie-men-s-plain-chest-panel-zipper-sweatshirt-hoodie-292734-1605612108.jpg',
        price: 120,
        stock: 0,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: ['High quality product','Pure cotton','Fit size','Machine wash'],
      },
      {
        _id: '2',
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: 'https://images.bewakoof.com/t320/iron-gate-basic-hoodie-sweatshirt-men-s-plain-hoodie-sweatshirt-283408-1606395885.jpg',
        price: 100,
        stock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: ['High quality product','Pure cotton','Fit size','Machine wash'],
      },
      {
        _id: '3',
        name: 'Lacoste Free Shirt',
        category: 'Shirts',
        image: 'https://images.bewakoof.com/t320/black-white-chest-panel-zipper-sweatshirt-hoodie-men-s-plain-chest-panel-zipper-sweatshirt-hoodie-292734-1605612108.jpg',
        price: 220,
        stock: 0,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: ['High quality product','Pure cotton','Fit size','Machine wash'],
      },
      {
        _id: '4',
        name: 'Nike Slim Pant',
        category: 'Pants',
        image: 'https://images.bewakoof.com/t320/black-side-panel-cut--sew-hoodie-sweat-shirt-men-s-plain-cut--sew-sweatshirt-hoodie-283543-1606396007.jpg',
        price: 78,
        stock: 15,
        brand: 'Nike',
        rating: 3.5,
        numReviews: 14,
        description: ['High quality product','Pure cotton','Fit size','Machine wash'],
      },
      {
        _id: '5',
        name: 'Puma Slim Pant',
        category: 'Pants',
        image: 'https://images.bewakoof.com/t320/white-hoodie-sweatshirt-men-s-plain-hoodie-sweatshirt-300509-1608288812.jpg',
        price: 65,
        stock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: ['High quality product','Pure cotton','Fit size','Machine wash'],
      },
      {
        _id: '6',
        name: 'Adidas Fit Pant',
        category: 'Pants',
        image: 'https://images.bewakoof.com/t540/men-s-half-sleeve-melange-hoodie-t-shirt-men-s-plain-half-sleeve-melange-hoodie-t-shirt-283492-1611130254.jpg',
        price: 139,
        stock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: ['High quality product','Pure cotton','Fit size','Machine wash'],
      },
    ],
  };
  export default data;